### ISSUE TITLE
Create prov document from Auditd log

### ISSUE THREAD

**Issue by klug0xy** [trungdong/notebooks#1]
Hello Sir,

Is possible to generate a prov document from the Auditd log ? if it is can you help with some advices and guidance please ? (i use the python library)

Houssem MJID
Thank you
Best regards

**Comment by trungdong** [comment]
Sorry, I'm not familiar with Auditd.

However, there is a tool to generate provenance from logged values. Please refer to https://lucmoreau.wordpress.com/2017/03/30/prov-template-a-quick-start/ for a tutorial.
You first need to design what the provenance of your application looks like and extract the required values from the logs. Then, the PROV-Template tool will do the provenance generation for you.
