### ISSUE TITLE
Is it possible to add a labeled arrow to an attribute?

### ISSUE THREAD

**Issue by ssaneei** [trungdong/notebooks#3]
I want to implement something like the example of [http://nidm.nidash.org/specs/img/Small_imaging_example.png](url) but I have a problem with the bottom right part. There, the MRI Scanner is attached to Field Strength with a dotted line and then field Scanner itself has two connection with concepts other than entity, activity, agent. Do you have any suggestions for the implementation? 
Somehow same issue with the top left part, where there are labels on dotted lines. Though some of these relations were not defined in provpy.

**Comment by trungdong** [comment]
I'm struggling to find the diagram you referred to in the 78-slide deck. Could you post an example diagram/image here?

**Comment by ssaneei** [comment]
![image](https://user-images.githubusercontent.com/48122137/123977051-f60d1c00-d9be-11eb-972e-612da212a8d3.png)

**Comment by trungdong** [comment]
Thanks. This looks like a manually drawn diagram where the author added those arrows in 
The PROV Python library supports only PROV relations (i.e. the "arrows" in diagram). It would not know other properties that could be rendered as arrows.
