### ISSUE TITLE
Where's the tutorial?

### ISSUE THREAD

**Issue by Marcos-AV** [trungdong/notebooks#4]
Hello, there!

Can you tell me where is the tutorial you mention in the documentation [1]?

The link [2] that you provide there is broken.

Thanks in advance!

[1] https://trungdong.github.io/prov-python-short-tutorial.html
[2] https://nbviewer.ipython.org/github/trungdong/notebooks/blob/master/PROV%20Tutorial.ipynb

**Comment by trungdong** [comment]
The links to the tutorial in [1] still work for me.
In any case, here is the link: https://nbviewer.org/github/trungdong/notebooks/blob/master/PROV%20Tutorial.ipynb

[2] does not work with `https://`. Where did you find it?

**Comment by Marcos-AV** [comment]
Thanks for the (very) fast reply. I found the links in the documentation itself [1]:

![image](https://github.com/trungdong/notebooks/assets/47954274/854afa15-b39c-4722-89c8-ed3dce4252a6)

They are pointing to a slight different address than the one you just sent and result in an HTTP error: ERR_TOO_MANY_REDIRECTS

**Comment by trungdong** [comment]
Thank you. It's probably a browser-specific behaviour (mine is Safari). The links on the blog post use `http://`, which redirects correctly. The `https://` version, however, does not.

In any case, I'll update the blog post to avoid this.

**Comment by Marcos-AV** [comment]
Now that you mentioned it, I just confirmed that it's a browser-related issue. The links worked on Firefox, but not in Opera, Chrome or Edge.
